;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

;;; Code:

(specifications->manifest
  (list "adb"
        "aflplusplus"
        "ascii"
        "awscli-2"
        "binutils"
        "binwalk"
        "buildah"
        "curl-ssh"
        "diffoscope"
        "my-emacs-next"
        "guile-emacs"
        "emacs-alert"
        "emacs-bluetooth"
        "emacs-buffer-env"
        "emacs-calibredb"
        "emacs-casual-calc"
        "emacs-citar" "emacs-citar-denote"
        "emacs-dape"
        "emacs-disproject"
        "emacs-ednc"
        "emacs-elisp-autofmt"
        "emacs-ement"
        "emacs-emms"
        "emacs-exwm"
        "emacs-forge"
        "emacs-helpful"
        "emacs-go-mode"
        "emacs-jinx"
        "emacs-magit" ;; depends on emacs-transient
        "emacs-mentor"
        "emacs-ob-go"
        "emacs-org-caldav"
        "emacs-org-contacts"
        "emacs-org-vcard"
        "emacs-osm"
        "emacs-polymode" "emacs-polymode-org"
        "emacs-tempel" "emacs-eglot-tempel"
        "emacs-verb"
        "emacs-x509-mode"
        "espeak-ng"
     ;; "ffmpeg" propagated by mpv
        "file"
        "flac"
        "flashrom"
        "fontconfig"
        "font-google-noto-emoji"
        "font-iosevka-term-slab"
        "font-liberation"
        "font-wqy-zenhei"
        "freerdp"
        "gcc"
        "gdb"
        "glibc"
        "gnuradio"
        "go"
        "gopls"
        "delve" ;; go debugger
        "graphviz"
        "emacs-graphviz-dot-mode"
        "guile-aws"
        "imagemagick"
        "iw"
        "libfaketime"
        "llvm"
        "clang"
        "lldb"
        "man-pages"
        "mariadb"
        "mit-krb5"
        "monero"
        "mpv"
        "mu"
        "emacs-mu4e-alert"
        "mysql"
        "node"
        "openjdk"
        "openocd"
        "openssh"
        "openvpn"
        "patch"
        "patchelf"
        "pinentry-emacs"
        "poke"
        "emacs-poke-mode"
        "pwntools"
        "python-debugpy"
        "python-ipython"
        "python-pycryptodomex"
        "python-requests"
        "python-scapy"
        "qemu"
        "retroarch" "libretro-dolphin-emu" "libretro-mupen64plus-nx"
        "rizin"
        "rr"
        "rust"
        "rust-analyzer"
        "emacs-rust-mode"
        "sage"
        "emacs-sage-shell-mode"
        "samba"
        "shellcheck"
        "emacs-shellcheck-flymake"
        "sigrock-cli"
        "skopeo"
        "socat"
        "squashfs-tools"
        "sshfs"
        "steam-client"
        "tesseract-ocr"
        "tiled"
        "tree-sitter-c"
        "tree-sitter-cpp"
        "tree-sitter-dockerfile"
        "tree-sitter-go"
        "tree-sitter-go-mod"
        "tree-sitter-javascript"
        "tree-sitter-org"
        "tree-sitter-php"
        "tree-sitter-rust"
        "unrar"
        "upx"
        "valkey"
        "wine64-staging"
        "wireguard-tools"
        "wireshark"
        "yt-dlp"
        "zbar"))

;;; dev-phone-manifest.scm ends here
